import primary from "./images/logoo.webp";
import mapss from "./images/flag.png";
import pic1 from "./images/1.jpg";
import pic2 from "./images/2.jpg";
import pic3 from "./images/3.jpg";

const CardData = [
  {
    id: 1,
    photo: pic1,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic2,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic3,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic2,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic1,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic2,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 1,
    photo: pic3,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
  {
    id: 2,
    photo: pic2,
    mapz: mapss,
    name: "Marco N.",
    work: "Medical Biller",
    skill1: "Problem Solving Skills.",
    skill2: "Critical Thinking Skills",
    skill3: "Emotional Intelligence",
    skill4: "Organization Skills",
    skill5: "Tact, discretion",
  },
];
export default CardData;
